import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({ adapter }) as unknown as InstanceType<
  typeof PrismaClient
>;

const sampleWorks = [
  {
    title: "Coastal Dawn",
    artistName: "Sarah Chen",
    workType: "synograph" as const,
    dimensionsInches: { width: 24, height: 36 },
    orientation: "portrait" as const,
    aiTagsHero: [
      "coastal",
      "sunrise",
      "ocean",
      "serene",
      "blue",
      "warm tones",
      "horizon",
      "water",
      "peaceful",
      "nature",
    ],
    aiTagsHidden: [
      "beach",
      "dawn",
      "morning light",
      "seascape",
      "pastel",
      "calm",
      "meditation",
      "living room",
      "bedroom",
      "spa",
      "tranquil",
      "soft",
      "golden hour",
      "reflections",
      "minimalist",
      "contemporary",
      "atmospheric",
      "coastal decor",
      "nautical",
      "summer",
    ],
    dominantColors: [
      { r: 135, g: 186, b: 215 },
      { r: 245, g: 198, b: 142 },
      { r: 72, g: 120, b: 165 },
      { r: 255, g: 235, b: 205 },
      { r: 100, g: 150, b: 180 },
    ],
    status: "active" as const,
  },
  {
    title: "Blue Horizon",
    artistName: "Mark Rivera",
    workType: "work_on_canvas" as const,
    dimensionsInches: { width: 30, height: 40 },
    orientation: "portrait" as const,
    retailerExclusive: "RH",
    aiTagsHero: [
      "abstract",
      "blue",
      "contemporary",
      "bold",
      "textured",
      "deep blue",
      "layered",
      "expressive",
      "modern",
      "large scale",
    ],
    aiTagsHidden: [
      "indigo",
      "navy",
      "cobalt",
      "gestural",
      "impasto",
      "acrylic",
      "office",
      "lobby",
      "dramatic",
      "moody",
      "masculine",
      "sophisticated",
      "statement piece",
      "color field",
      "abstract expressionism",
      "winter",
      "depth",
      "ocean inspired",
      "jewel toned",
      "luxury",
    ],
    dominantColors: [
      { r: 25, g: 55, b: 120 },
      { r: 60, g: 95, b: 170 },
      { r: 15, g: 35, b: 80 },
      { r: 100, g: 140, b: 200 },
      { r: 40, g: 70, b: 140 },
    ],
    status: "active" as const,
  },
  {
    title: "Summer Roses",
    artistName: "Emma Liu",
    workType: "work_on_paper" as const,
    dimensionsInches: { width: 18, height: 24 },
    orientation: "portrait" as const,
    aiTagsHero: [
      "floral",
      "roses",
      "botanical",
      "pink",
      "delicate",
      "romantic",
      "garden",
      "watercolor",
      "feminine",
      "spring",
    ],
    aiTagsHidden: [
      "flowers",
      "petals",
      "still life",
      "blush",
      "pastel pink",
      "soft",
      "bedroom",
      "nursery",
      "powder room",
      "traditional",
      "cottage",
      "english garden",
      "impressionist",
      "light",
      "airy",
      "fresh",
      "elegant",
      "graceful",
      "wedding",
      "gift",
    ],
    dominantColors: [
      { r: 230, g: 180, b: 190 },
      { r: 200, g: 120, b: 140 },
      { r: 245, g: 230, b: 235 },
      { r: 80, g: 130, b: 80 },
      { r: 255, g: 245, b: 245 },
    ],
    status: "active" as const,
  },
  {
    title: "Urban Grid No. 7",
    artistName: "James Okafor",
    workType: "synograph" as const,
    dimensionsInches: { width: 36, height: 36 },
    orientation: "square" as const,
    aiTagsHero: [
      "geometric",
      "urban",
      "grid",
      "monochrome",
      "architectural",
      "structured",
      "modern",
      "minimal",
      "graphic",
      "black and white",
    ],
    aiTagsHidden: [
      "lines",
      "pattern",
      "city",
      "industrial",
      "concrete",
      "brutalist",
      "office",
      "commercial",
      "loft",
      "mid-century",
      "bauhaus",
      "constructivist",
      "graphic design",
      "neutral",
      "contemporary art",
      "wall art",
      "masculine",
      "professional",
      "clean",
      "stark",
    ],
    dominantColors: [
      { r: 30, g: 30, b: 30 },
      { r: 200, g: 200, b: 200 },
      { r: 120, g: 120, b: 120 },
      { r: 245, g: 245, b: 245 },
      { r: 80, g: 80, b: 80 },
    ],
    status: "active" as const,
  },
  {
    title: "Meadow at Dusk",
    artistName: "Sarah Chen",
    workType: "synograph" as const,
    dimensionsInches: { width: 40, height: 30 },
    orientation: "landscape" as const,
    aiTagsHero: [
      "landscape",
      "meadow",
      "dusk",
      "golden",
      "pastoral",
      "warm",
      "grass",
      "sunset",
      "countryside",
      "atmospheric",
    ],
    aiTagsHidden: [
      "field",
      "wildflowers",
      "evening",
      "twilight",
      "amber",
      "honey",
      "earth tones",
      "living room",
      "dining room",
      "rustic",
      "farmhouse",
      "cozy",
      "nostalgic",
      "romantic",
      "plein air",
      "impressionist",
      "warm palette",
      "autumn",
      "harvest",
      "peaceful",
    ],
    dominantColors: [
      { r: 180, g: 150, b: 80 },
      { r: 120, g: 140, b: 70 },
      { r: 220, g: 180, b: 100 },
      { r: 200, g: 120, b: 60 },
      { r: 160, g: 170, b: 90 },
    ],
    status: "active" as const,
  },
  {
    title: "Fragments in Red",
    artistName: "Mark Rivera",
    workType: "work_on_canvas" as const,
    dimensionsInches: { width: 48, height: 36 },
    orientation: "landscape" as const,
    aiTagsHero: [
      "abstract",
      "red",
      "bold",
      "energetic",
      "contemporary",
      "dynamic",
      "large",
      "expressive",
      "vivid",
      "passionate",
    ],
    aiTagsHidden: [
      "crimson",
      "scarlet",
      "vermillion",
      "gestural",
      "action painting",
      "lobby",
      "restaurant",
      "hotel",
      "statement",
      "dramatic",
      "power",
      "intensity",
      "fire",
      "movement",
      "abstract expressionism",
      "de kooning",
      "warm",
      "aggressive",
      "impact",
      "luxury",
    ],
    dominantColors: [
      { r: 200, g: 40, b: 40 },
      { r: 160, g: 30, b: 50 },
      { r: 240, g: 80, b: 60 },
      { r: 120, g: 20, b: 30 },
      { r: 255, g: 120, b: 90 },
    ],
    status: "active" as const,
  },
  {
    title: "Eucalyptus Study",
    artistName: "Lily Nakamura",
    workType: "work_on_paper" as const,
    dimensionsInches: { width: 16, height: 20 },
    orientation: "portrait" as const,
    aiTagsHero: [
      "botanical",
      "eucalyptus",
      "green",
      "minimal",
      "natural",
      "organic",
      "delicate",
      "fresh",
      "plant",
      "study",
    ],
    aiTagsHidden: [
      "leaves",
      "branches",
      "sage",
      "mint",
      "muted green",
      "watercolor",
      "bathroom",
      "kitchen",
      "spa",
      "scandinavian",
      "japandi",
      "wabi sabi",
      "botanical illustration",
      "nature study",
      "calm",
      "zen",
      "wellness",
      "clean",
      "simple",
      "understated",
    ],
    dominantColors: [
      { r: 140, g: 170, b: 140 },
      { r: 180, g: 200, b: 175 },
      { r: 100, g: 135, b: 110 },
      { r: 230, g: 235, b: 225 },
      { r: 160, g: 185, b: 155 },
    ],
    status: "active" as const,
  },
  {
    title: "Night Harbor",
    artistName: "James Okafor",
    workType: "photography" as const,
    dimensionsInches: { width: 36, height: 24 },
    orientation: "landscape" as const,
    aiTagsHero: [
      "photography",
      "harbor",
      "night",
      "reflections",
      "moody",
      "urban",
      "water",
      "lights",
      "atmospheric",
      "dark",
    ],
    aiTagsHidden: [
      "marina",
      "boats",
      "docks",
      "cityscape",
      "neon",
      "long exposure",
      "cinematic",
      "film noir",
      "office",
      "man cave",
      "den",
      "bachelor pad",
      "contemporary",
      "dramatic",
      "mysterious",
      "evening",
      "cool tones",
      "deep blue",
      "purple",
      "street photography",
    ],
    dominantColors: [
      { r: 20, g: 25, b: 50 },
      { r: 60, g: 50, b: 80 },
      { r: 200, g: 180, b: 100 },
      { r: 40, g: 40, b: 70 },
      { r: 150, g: 130, b: 80 },
    ],
    status: "active" as const,
  },
  {
    title: "Terracotta Dreams",
    artistName: "Amara Diallo",
    workType: "synograph" as const,
    dimensionsInches: { width: 24, height: 30 },
    orientation: "portrait" as const,
    retailerExclusive: "CB2",
    aiTagsHero: [
      "abstract",
      "terracotta",
      "warm",
      "organic shapes",
      "earth tones",
      "contemporary",
      "mid-century",
      "desert",
      "sculptural",
      "muted",
    ],
    aiTagsHidden: [
      "burnt orange",
      "clay",
      "rust",
      "sienna",
      "adobe",
      "southwest",
      "bohemian",
      "living room",
      "entryway",
      "matisse",
      "organic",
      "curved",
      "neutral",
      "earthy",
      "natural",
      "warm palette",
      "autumn",
      "cozy",
      "textural",
      "handmade feel",
    ],
    dominantColors: [
      { r: 195, g: 120, b: 80 },
      { r: 220, g: 160, b: 120 },
      { r: 170, g: 90, b: 60 },
      { r: 240, g: 220, b: 200 },
      { r: 150, g: 80, b: 50 },
    ],
    status: "active" as const,
  },
  {
    title: "Reductive Composition No. 3",
    artistName: "Lily Nakamura",
    workType: "reductive" as const,
    dimensionsInches: { width: 30, height: 30 },
    orientation: "square" as const,
    aiTagsHero: [
      "reductive",
      "minimal",
      "geometric",
      "neutral",
      "subtle",
      "quiet",
      "contemplative",
      "texture",
      "monochrome",
      "refined",
    ],
    aiTagsHidden: [
      "beige",
      "cream",
      "white",
      "off-white",
      "linen",
      "plaster",
      "relief",
      "bedroom",
      "meditation room",
      "gallery",
      "museum quality",
      "agnes martin",
      "minimalism",
      "zen",
      "peaceful",
      "sophisticated",
      "luxury",
      "collector",
      "investment",
      "timeless",
    ],
    dominantColors: [
      { r: 235, g: 230, b: 220 },
      { r: 215, g: 210, b: 200 },
      { r: 245, g: 242, b: 238 },
      { r: 200, g: 195, b: 185 },
      { r: 225, g: 220, b: 212 },
    ],
    status: "active" as const,
  },
  {
    title: "Verdant Abstraction",
    artistName: "Amara Diallo",
    workType: "work_on_canvas" as const,
    dimensionsInches: { width: 36, height: 48 },
    orientation: "portrait" as const,
    aiTagsHero: [
      "abstract",
      "green",
      "lush",
      "organic",
      "layered",
      "tropical",
      "vibrant",
      "botanical",
      "rich",
      "depth",
    ],
    aiTagsHidden: [
      "emerald",
      "forest",
      "jungle",
      "foliage",
      "verdant",
      "palm",
      "monstera",
      "living room",
      "dining room",
      "hotel lobby",
      "biophilic",
      "nature inspired",
      "jewel toned",
      "saturated",
      "spring",
      "growth",
      "renewal",
      "exotic",
      "luxury",
      "statement piece",
    ],
    dominantColors: [
      { r: 40, g: 120, b: 60 },
      { r: 80, g: 160, b: 90 },
      { r: 20, g: 80, b: 40 },
      { r: 120, g: 180, b: 100 },
      { r: 60, g: 140, b: 70 },
    ],
    status: "active" as const,
  },
  {
    title: "Concrete Poetry",
    artistName: "James Okafor",
    workType: "photography" as const,
    dimensionsInches: { width: 24, height: 36 },
    orientation: "portrait" as const,
    aiTagsHero: [
      "photography",
      "architecture",
      "concrete",
      "brutalist",
      "geometric",
      "urban",
      "shadows",
      "monochrome",
      "structural",
      "imposing",
    ],
    aiTagsHidden: [
      "building",
      "facade",
      "modernist",
      "angles",
      "lines",
      "gray",
      "industrial",
      "office",
      "loft",
      "studio",
      "architect",
      "le corbusier",
      "stark",
      "powerful",
      "scale",
      "perspective",
      "black and white",
      "contrast",
      "dramatic",
      "editorial",
    ],
    dominantColors: [
      { r: 150, g: 150, b: 150 },
      { r: 100, g: 100, b: 100 },
      { r: 200, g: 200, b: 200 },
      { r: 60, g: 60, b: 60 },
      { r: 180, g: 180, b: 180 },
    ],
    status: "active" as const,
  },
];

async function main() {
  console.log("Seeding database with sample works...");

  // Generate SKUs
  const year = new Date().getFullYear();
  let skuCounter = 1;

  for (const work of sampleWorks) {
    const gpSku = `GP${year}${String(skuCounter).padStart(4, "0")}`;
    skuCounter++;

    await prisma.work.create({
      data: {
        gpSku,
        title: work.title,
        artistName: work.artistName,
        workType: work.workType,
        dimensionsInches: work.dimensionsInches,
        orientation: work.orientation,
        retailerExclusive: work.retailerExclusive || null,
        aiTagsHero: work.aiTagsHero,
        aiTagsHidden: work.aiTagsHidden,
        dominantColors: work.dominantColors,
        status: work.status,
        sourceType: "gp_original",
        // Using placeholder image URLs (gradient placeholders)
        imageUrlThumbnail: `https://placehold.co/300x400/f5f5f5/999?text=${encodeURIComponent(work.title)}`,
        imageUrlPreview: `https://placehold.co/1200x1600/f5f5f5/999?text=${encodeURIComponent(work.title)}`,
        imageUrlSource: `https://placehold.co/1200x1600/f5f5f5/999?text=${encodeURIComponent(work.title)}`,
      },
    });

    console.log(`  Created: ${gpSku} - ${work.title} by ${work.artistName}`);
  }

  console.log(`\nSeeded ${sampleWorks.length} works successfully.`);
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
